global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: htn
    static_configs:
      - targets: ["htn:9101"]     # admin port inside the compose network
